============================================================
  Generated by:           Genus(TM) Synthesis Solution 17.22-s017_1
  Generated on:           Dec 18 2023  12:06:50 pm
  Module:                 single_port_sync_ram
  Technology library:     tsl18fs120_scl_ff 1
  Operating conditions:   _nominal_ (balanced_tree)
  Wireload mode:          enclosed
  Area mode:              timing library
============================================================

       Pin             Type      Fanout  Load Slew Delay Arrival   
                                         (fF) (ps)  (ps)   (ps)    
-------------------------------------------------------------------
(clock clk)           launch                                   0 R 
(in_del_1)            ext delay                       +0       0 R 
cs                    in port         2   5.2    0    +0       0 R 
g3932/I                                               +0       0   
g3932/ZN              inv0d0          1   4.2   47   +29      29 F 
g3912__7114/A2                                        +0      29   
g3912__7114/ZN        nr02d1          3  12.0  138   +72     101 R 
g3911/I                                               +0     101   
g3911/ZN              inv0d1         33 161.0  413  +224     325 F 
g3896__8780/A2                                        +0     325   
g3896__8780/ZN        nr02d1          4  10.7  164  +130     455 R 
g3892/I                                               +0     455   
g3892/ZN              inv0d0          5  21.0  209  +128     582 F 
g3878__8780/A2                                        +0     582   
g3878__8780/ZN        nr02d1         32 156.8 1316  +610    1192 R 
g3852__5266/B2                                        +0    1192   
g3852__5266/ZN        aoi22d1         1   4.0  228   +59    1251 F 
g3594__2683/A4                                        +0    1251   
g3594__2683/ZN        nd04d1          1   2.8  114   +90    1341 R 
g3019__9906/A2                                        +0    1341   
g3019__9906/Z         or02d0          1   2.0   38   +66    1408 R 
tmp_data_reg[27]/D    dfnrb1                          +0    1408   
tmp_data_reg[27]/CP   setup                      0   +36    1443 R 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
(clock clk)           capture                              20000 R 
-------------------------------------------------------------------
Cost Group   : 'clk' (path_group 'clk')
Timing slack :   18557ps 
Start-point  : cs
End-point    : tmp_data_reg[27]/D
