============================================================
  Generated by:           Genus(TM) Synthesis Solution 17.22-s017_1
  Generated on:           Dec 18 2023  12:06:50 pm
  Module:                 single_port_sync_ram
  Technology library:     tsl18fs120_scl_ff 1
  Operating conditions:   _nominal_ (balanced_tree)
  Wireload mode:          enclosed
  Area mode:              timing library
============================================================

                            Leakage    Dynamic      Total    
      Instance       Cells Power(nW)  Power(nW)   Power(nW)  
-------------------------------------------------------------
single_port_sync_ram  1499    85.134 4710695.227 4710780.361 

