============================================================
  Generated by:           Genus(TM) Synthesis Solution 17.22-s017_1
  Generated on:           Dec 18 2023  12:06:50 pm
  Module:                 single_port_sync_ram
  Technology library:     tsl18fs120_scl_ff 1
  Operating conditions:   _nominal_ (balanced_tree)
  Wireload mode:          enclosed
  Area mode:              timing library
============================================================

      Instance       Module  Cell Count  Cell Area  Net Area   Total Area  Wireload     
----------------------------------------------------------------------------------------
single_port_sync_ram               1499  53518.941     0.000    53518.941    <none> (D) 

 (D) = wireload is default in technology library
